version: '3.9'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - backend

  bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    command: python runbot.py
    depends_on:
      - web
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - web
    networks:
      - backend


networks:
  backend:

volumes:
  mongo_data:
